"""empty message

Revision ID: 346ad415721c
Revises: 8a82c5355b3c
Create Date: 2021-03-22 20:10:09.209246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346ad415721c'
down_revision = '8a82c5355b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'type', 'courier', ['courier_id'], ['courier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.drop_column('type', 'courier_id')
    # ### end Alembic commands ###
