"""empty message

Revision ID: 394fcebbd3d1
Revises: 346ad415721c
Create Date: 2021-03-25 00:52:58.489626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '394fcebbd3d1'
down_revision = '346ad415721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('assign', sa.String(length=30), nullable=True),
    sa.Column('complete', sa.String(length=30), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('order')
    op.drop_constraint('preferred_time_order_id_fkey', 'preferred_time', type_='foreignkey')
    op.create_foreign_key(None, 'preferred_time', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preferred_time', type_='foreignkey')
    op.create_foreign_key('preferred_time_order_id_fkey', 'preferred_time', 'order', ['order_id'], ['order_id'])
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('region', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assign', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('complete', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], name='order_courier_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='order_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
