"""empty message

Revision ID: 468a1ebfb400
Revises: 394fcebbd3d1
Create Date: 2021-03-26 22:39:37.617933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468a1ebfb400'
down_revision = '394fcebbd3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coef', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coef')
    # ### end Alembic commands ###
