"""empty message

Revision ID: 7dbb13e5d7c2
Revises: bb1166c0df6a
Create Date: 2021-03-28 13:51:05.640557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbb13e5d7c2'
down_revision = 'bb1166c0df6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bunch_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bunch_complete')
    # ### end Alembic commands ###
